[toolchain]
channel = "nightly-2025-09-19" # One day post 1.90.0
components = ["rust-src", "clippy", "rustfmt", "rust-docs"]

[tools]
cargo-deny = "^0.17"
cargo-make = "0.37.21"
cargo-release = "0.25.12"
cargo-llvm-cov = "0.6.18"
